### PR TITLE
Correct typo in the "Import data" documentation page

### PR DESCRIPTION
**Pull request by abdesselam-benameur**
The documentation talks about the .dynamic() method to create a dynamic batcher but the code uses rate_limit batcher

Link of the webpage: https://weaviate.io/developers/academy/py/starter_text_data/text_collections/import_data#:~:text=This%20example%20uses,objects%20per%20minute.

### What's being changed:

image

### Type of change:

- **Documentation** updates (non-breaking change to fix/update documentation)

### CODE REVIEW

**Comment by daveatweaviate** [comment]
Hi @abdesselam-benameur, thanks for taking the time to contribute to our docs. 

Have you had a chance to review our [Contributors' Agreement](https://weaviate.io/service/contributor-license-agreement)?

Would you acknowledge that you accept the agreement? Then we can merge your PR.

**Comment by daveatweaviate** [comment]
Hi @abdesselam-benameur, we'd like to recognize your contribution to the docs.

Would you leave a comment to accept the [Contributors' Agreement](https://weaviate.io/service/contributor-license-agreement)? We can't merge your PR without it.

Thanks!

**Comment by abdesselam-benameur** [comment]
Hello

yes I accept it

Best regards !

Le lun. 10 juin 2024 à 22:46, daveatweaviate ***@***.***> a
écrit :

**Comment by daveatweaviate** [comment]
@abdesselam-benameur, thank you for taking the time to contribute this update. I've merged your PR branch.

**Pull request merged**
