### PR TITLE
Go examples aggregation

### PR DESCRIPTION
**Pull request by donomii**
### Type of change:

- [ ] **Documentation** updates (non-breaking change to fix/update documentation)
- [ ] **Website** updates (non-breaking change to update main page, company pages, pricing, etc)
- [ ] **Content** updates – **blog**, **podcast** (non-breaking change to add/update content)
- [ ] **Bug fix** (non-breaking change to fixes an issue with the site)
- [ ] **Feature** or **enhancements** (non-breaking change to add functionality)

### How Has This Been Tested?

- [ ] **GitHub action** – automated build completed without errors
- [ ] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

### CODE REVIEW

**Comment by daveatweaviate** [comment]
[staging](https://go-examples-aggregation--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/search/aggregate)

**Comment by donomii** [comment]
The go imports are a difficult for users, should we add import suggestions to all of the examples?

**Comment by daveatweaviate** [comment]
Good question. To be honest, we don't have a clear answer.

I think we only need to do it when we introduce something unusual, in this case filters was an addition to the basic set of

```shell
"github.com/weaviate/weaviate-go-client/v4/weaviate"
"github.com/weaviate/weaviate-go-client/v4/weaviate/auth"
"github.com/weaviate/weaviate-go-client/v4/weaviate/graphql"
```

**Comment by donomii** [comment]
I feel like we should have one complete example on the page, so people can cut and paste a working program.  I do realise that is a lot more work, though

**Comment by daveatweaviate** [comment]
I'll discuss that with Sebastian and JP. We could maybe add one at the bottom of each of the HowTo pages.

**Comment by antas-marcin** [comment]
@donomii Could you fix the indentation of the Go examples also here in this PR (this is how they [look](https://go-examples-aggregation--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/search/aggregate#retrieve-the-count-meta-property) rn)

**Comment by donomii** [comment]
> @donomii Could you fix the indentation of the Go examples also here in this PR (this is how they [look](https://go-examples-aggregation--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/search/aggregate#retrieve-the-count-meta-property) rn)

Done

**Review by antas-marcin — APPROVED** [review]

**Pull request merged**
