### PR TITLE
docs: update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by asmitbm**
### Why:

Earlier CONTRIBUTING.md had old way of committing messages. I updated the docs with new way of committing messages which follows industry standards and commit messages look more consistent. Also renamed `readme.md` to `README.md` to make contributor files look consistent to each other.

### Type of change:

- [x] Documentation updates (non-breaking change which updates documents)

### How Has This Been Tested?

No tests required for this

### CODE REVIEW

**Comment by Asmit2952** [comment]
Hey @bobvanluijt can you tell me what conflicts that file has?

**Comment by bobvanluijt** [comment]
@Asmit2952 – yeah, it's just in the readme file. I think that simply closing and recreating the PR (based on the latest version in `main`) solves the problem

**Comment by Asmit2952** [comment]
> @Asmit2952 – yeah, it's just in the readme file. I think that simply closing and recreating the PR (based on the latest version in `main`) solves the problem

Cool, I'll rebase and push a new commit or create an entirely new PR.

**Comment by Asmit2952** [comment]
> @Asmit2952 Did you create a new PR in the end? If yes, could you close this one? If no, is this PR still relevant?

Hey @laura-ham can you tell me what are the merge conflicts specifically? I am not getting any info on this side.
Screenshot (344)

**Comment by laura-ham** [comment]
@Asmit2952 You can click on `readme.md` in that window, and the file opens with the conflicts highlighted. You can then solve it in there.

**Comment by Asmit2952** [comment]
> @Asmit2952 You can click on `readme.md` in that window, and the file opens with the conflicts highlighted. You can then solve it in there.

That `readme.md` is not clickable. I'll try to rebase and force push

**Pull request closed without merging**
