### PR TITLE
update benchmark results

### PR DESCRIPTION
**Pull request by StefanBogdan**
### What's being changed:

The benchmark results: new benchmark results to be published with latest Weaviate version and new infrastructure.

### Type of change:

- [x] **Documentation** updates (non-breaking change to fix/update documentation)

### How Has This Been Tested?

- [x] **GitHub action** – automated build completed without errors
- [x] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

### CODE REVIEW

**Comment by StefanBogdan** [comment]
For this PR I would need some help with the results we want to show on the documentation page. Currently it has **ALL** the results that were collected which is more than we would need to show. The results are stored in the new `ann-{dataset}.mdx` files.

Another thing that needs to be checked is the **Recommended configuration** for each dataset. I chose one that looked pretty balanced to me but let me know if there is a better one I can use.

And the last thing is the **QPS vs Recall** plots. Currently it is just PNG photo. I can create PNGs that have a transparent background with either black or white axes and text, the only thing I could not figure out is how can I switch between the black or white image depending on the light/dark mode used. Let me know if we want to further investigate how to achieve different plots depending on the mode used.

**Comment by StefanBogdan** [comment]
Here is the link to this docs version: https://stefan-update-benchmark--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/benchmarks/ann

**Comment by databyjp** [comment]
Amazing. I will take a look later this week (was away last week), thanks so much @StefanBogdan !

**Comment by StefanBogdan** [comment]
[Here](https://stefan-update-benchmark--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/benchmarks/ann) is the live lint to the website.

**Pull request merged**
