### PR TITLE
Adds curl example

### LINKED ISSUE #1117: Add cURL cross reference example
### What part of document/web-page on weaviate.io is affected?

There is a cURL example [here](https://weaviate.io/developers/weaviate/api/rest/objects#cross-references). 
There should be one [here](https://weaviate.io/developers/weaviate/manage-data/cross-references#retrieve-crossreferences) as well.

Sample to add a reference

```
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"beacon": "weaviate://localhost/<REFERENCED_CLASS_NAME>/<REFERENCED_OBJECT_UUID>" }' \
    https://<WEAVIATE_URI>/v1/objects/<REFERENCING_CLASS_NAME>/<REFERENCING_OBJECT_UUID>/references/<REFERENCED_CLASS_PROPERY>?consistency_level=ALL[,tenant=<TENANT_ID>]

Lets say you have class A with property toB, another class B that A will reference, and no Multi tenancy enabled. The curl will look like this:

curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"beacon": "weaviate://localhost/B/<B_OBJECT_UUID>" }' \
    https://<WEAVIATE_URI>/v1/objects/A/<A_OBJECT_UUID>/references/toB?consistency_level=ALL
```

[slack](https://weaviate-org.slack.com/archives/C04LB3DLSSG/p1694679565914979)

### PR DESCRIPTION
**Pull request by ankur0904**
### What's being changed:

Fix #1117 
Add the `cURL` cross reference example.
Screenshot from 2023-11-11 11-19-51

### Type of change:

- [x] **Documentation** updates (non-breaking change to fix/update documentation)

### How Has This Been Tested?
- [x] **Local build** - the site works as expected when running `yarn start`

### CODE REVIEW

**Comment by daveatweaviate** [comment]
@ankur0904 thanks for sending in the PR. I'll have a look at it. In the meantime, have you agreed to the [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement)?

**Comment by ankur0904** [comment]
@weaviate-git-bot I agree with the CLA.

**Review by daveatweaviate — COMMENTED** [review]
@ankur0904 Thanks for your PR, this is a great start. Would you adjust the formatting on it so it matches the style of our other examples? 

You can probably use the same localhost address that you use to test the syntax on your machine. 

Thanks!

**Comment by ankur0904** [comment]
@daveatweaviate Made the required changes :)

**Comment by daveatweaviate** [comment]
@ankur0904  Thanks for your contribution to the docs. You may have noticed that we've just finished refactoring this section. Unfortunately, we decided not to include cURl examples for now, so I'm going to close this PR without merging it in.

We do appreciate your efforts, and thank you once again for your time and interest.

**Comment by ankur0904** [comment]
@daveatweaviate 
It's alright. 

Thank you too.

**Pull request closed without merging**
