### PR TITLE
Fix WCS quickstart for JS/TS Beta

### LINKED ISSUE #1857: VCS Quickstart page doesn't have a code snippet for JS/TS (Beta)
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### Steps to reproduce the bug

1. Go to https://weaviate.io/developers/wcs/quickstart
2. Select "JS/TS (Beta)" in the "Install a client library" section
3. Note that in the "Connect to your WCS instance" section, the tab "JavaScript/TypeScript" is now selected

Its import 

```
import weaviate, { WeaviateClient, ObjectsBatcher, ApiKey } from 'weaviate-ts-client';
```

won't work for JS/TS (Beta). It should be 

```
import weaviate, { WeaviateClient } from 'weaviate-client';
```

### Expected behavior

Add a separate tab with an example covering `weaviate-client`

### Screenshots

image

### Additional context?

_No response_

### PR DESCRIPTION
**Pull request by mikhailshilkov**
### What's being changed:

Fix #1857

Result built locally:

image

### Type of change:

- [x] **Documentation** updates (non-breaking change to fix/update documentation)

### How Has This Been Tested?

- [x] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
I agree with the CLA

**Comment by databyjp** [comment]
@malgamves if you wouldn't mind taking a look at this also :)

**Comment by malgamves** [comment]
not sure where this populates, what page were you looking at @mikhailshilkov ?
also thanks for trying out the new client and helping with the documentation.

PR looks good! Just curious what page it affects, a lot of the markdown files are referenced in multiple places.

**Comment by databyjp** [comment]
Thanks @malgamves - I usually run a search for the filename like this:

image

I'll run the workflow & merge when done :D

**Pull request merged**
