### PR TITLE
Building Multimodal AI in TypeScript

### PR DESCRIPTION
**Pull request by malgamves**
### What's being changed:

I added a new blog file, two screenshots and a gif. i also added my author profile and image.
### Type of change:

- [x] **Content** updates – **blog**, **podcast** (non-breaking change to add/update content)

### How Has This Been Tested?

- [ ] **Github action** – automated build completed without errors
- [x] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

### CODE REVIEW

**Comment by malgamves** [comment]
Writing finishing touches and then we're good to merge and publish

**Review by erika-cardenas — APPROVED** [review]
LGTM!

**Comment by malgamves** [comment]
Awesome @erika-cardenas - just ran spell check, we should be good to go!

**Comment by malgamves** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the Weaviate bot 👋🤖PS:Are you already a member of the [Weaviate Slack channel?](https://weaviate.io/slack)

Yesss I agree with the CLA 😄

**Pull request merged**
